#!/bin/bash
if [ "$1" == "" ]; then
    echo "Usage: tabutils COMMAND"
    echo ""
    echo "Commands"
    echo "    filter - Filters a tab-delmited file based upon critera"
    echo "    merge  - Merges tab-delimited files together, combining common columns"
    echo "    view   - A data aware tab-delimited file viewer"
    echo ""
    echo "See 'tabutils help CMD' for more information about a specific command"
    exit -1
fi

if [ "$1" == "help" ]; then
    action=tab_$2.py
    `dirname $0`/tab_utils/$action -h
else
    action=tab_$1.py
    shift

    `dirname $0`/tab_utils/$action $@
fi
